from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime
from enum import Enum


class PositionSide(str, Enum):
    LONG = "long"
    SHORT = "short"


class OrderSide(str, Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(str, Enum):
    MARKET = "market"
    LIMIT = "limit"
    STOP_MARKET = "STOP_MARKET"
    TAKE_PROFIT_MARKET = "TAKE_PROFIT_MARKET"


class SignalDirection(str, Enum):
    BUY = "buy"
    SELL = "sell"
    NONE = "none"


@dataclass
class Position:
    """
    Represents an open derivative position.
    """

    symbol: str
    side: PositionSide
    amount: float
    entry_price: float
    unrealized_pnl: float = 0.0
    liquidation_price: Optional[float] = None


@dataclass
class Order:
    """
    Represents an exchange order (open or closed).
    """

    id: str
    symbol: str
    side: OrderSide
    amount: float
    price: Optional[float]
    status: str
    type: OrderType = OrderType.MARKET
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class Trade:
    """
    Represents a completed trade (entry + exit).
    """

    symbol: str
    entry_price: float
    exit_price: float
    amount: float
    side: PositionSide
    pnl: float
    entry_time: datetime
    exit_time: datetime
    reason: str = "Signal"


@dataclass
class TradeSignal:
    """
    Represents a trading signal generated by a Strategy.
    """

    direction: SignalDirection
    price: float
    stop_loss: float
    take_profit: float
    reason: str
    confidence: float = 1.0
