_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[-0.08844631 -0.20254582 -0.30964577 -0.39432687  0.03328106
           -0.2024315  -0.30930042  1.2559111  -0.53677773]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000002098426C160>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 5000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.25.0
        code_path: source-trading-bot-c__Users_mwaqa_Desktop_Bot_train_agent.ipynb
        e:
            7ieiu7y8pr3bw0qssjwsldoeu1qbmnk5:
                codePath: c:\Users\mwaqa\Desktop\Bot\train_agent.ipynb
                codePathLocal: train_agent.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510956400640"
                        used: "392779456512"
                email: muhammadwaqar666@gmail.com
                executable: c:\Users\mwaqa\miniconda3\envs\trading_bot\python.exe
                git:
                    commit: c5975e4d86f7fe9b908df69911de6f9d4463ae3d
                    remote: https://github.com/mwaqar666/Bot.git
                host: Trinity
                memory:
                    total: "17019432960"
                os: Windows-10-10.0.26300-SP0
                program: c:\Users\mwaqa\Desktop\Bot\train_agent.ipynb
                python: CPython 3.10.19
                root: c:\Users\mwaqa\Desktop\Bot
                startedAt: "2026-02-26T14:48:01.244352Z"
                writerId: 7ieiu7y8pr3bw0qssjwsldoeu1qbmnk5
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 2
                - 16
                - 22
            "4": 3.10.19
            "5": 0.25.0
            "8":
                - 1
                - 3
            "12": 0.25.0
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Discrete(3)
algo:
    value: PPO
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x00000209B0019F60>
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_features:
    value: 9
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (1, 9), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=9, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=9, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=3, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000002098D5112D0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
sl_multiplier:
    value: 1
start_time:
    value: 1772117287490699900
target_kl:
    value: None
tensorboard_log:
    value: None
tp_multiplier:
    value: 2
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
window_size:
    value: 1
